# Generated by Django 4.2.7 on 2025-04-23 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='shows/')),
                ('category', models.CharField(choices=[('INDIAN', 'Indian'), ('HOLLYWOOD', 'Hollywood'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('release_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': [models.Case(models.When(category='INDIAN', then=0), models.When(category='HOLLYWOOD', then=1), default=2, output_field=models.IntegerField()), '-release_date'],
            },
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='shows.show')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=2)),
                ('number', models.IntegerField()),
                ('is_reserved', models.BooleanField(default=False)),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='shows.showtime')),
            ],
            options={
                'ordering': ['row', 'number'],
                'unique_together': {('showtime', 'row', 'number')},
            },
        ),
    ]
